language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - pip uninstall -y numpy
  - sudo apt-add-repository -y ppa:octave/stable
  - sudo apt-get update
  - sudo apt-get install -y -qq python-setuptools python-numpy python-scipy python-matplotlib python-tables python-nose python-coverage octave
  - pip install pandas==0.12.0 pyyaml oct2py==1.2.0 DynamicistToolKit==0.3.5
  - pip freeze
install:
  - python setup.py install
script: nosetests -v --with-coverage --cover-package=gaitanalysis
after_success: coveralls
