language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -y -qq python-setuptools python-numpy python-scipy python-matplotlib python-nose python-coverage
  - pip install cython pyyaml python-coveralls
  # I don't think pip will work for installing Pandas because it doesn't build
  # from source. It uses prebuilt Cython modules that link to a different NumPy
  # version, so we compile it ourselves.
  - git clone git://github.com/pydata/pandas.git
  - cd pandas && git checkout v0.12.0 && python setup.py install && cd ..
  - pip freeze
install:
  # DynamicistToolKit is pulled in during the following command, instead of
  # being preinstalled like the other dependencies.
  - python setup.py install
script: nosetests -v --with-coverage --cover-package=gaitanalysis
after_success: coveralls
